/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '松村　充規' at '16/11/14 10:31' with Gradle 2.14.1
 *
 * @author 松村　充規, @date 16/11/14 10:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
